name: Auto-Build
on:
  push:
    branches: [ master ]


jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set default Xamarin SDK versions
        run: $VM_ASSETS/select-xamarin-sdk-v2.sh
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 6.0.x

      
      - name: Install dependencies
        run: nuget restore DustyPig.Mobile.sln

      - name: Build Android
        run: msbuild DustyPig.Mobile/DustyPig.Mobile.Android/DustyPig.Mobile.Android.csproj /t:PackageForAndroid /p:Configuration=Debug

      - name: Build iOS
        run: msbuild DustyPig.Mobile/DustyPig.Mobile.iOS/DustyPig.Mobile.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild