name: Auto-Build
on:
  push:
    branches: [ master ]


jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: nuget restore DustyPig.Mobile.sln


      - name: Setup iOS Certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
          keychain: github-actions-xamarin
          keychain-password: ''

      - name: Setup iOS Provisioning Profiles
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id: 'tv.dustypig.dustypig'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    
      - name: Build iOS
        run: msbuild DustyPig.Mobile/DustyPig.Mobile.iOS/DustyPig.Mobile.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild


        
      - name: Build Android
        run: msbuild DustyPig.Mobile/DustyPig.Mobile.Android/DustyPig.Mobile.Android.csproj /t:PackageForAndroid /p:Configuration=Debug
