name: Release
on:
  workflow_dispatch:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 6.0.x

      - name: Build Android
        run: |
            run: dotnet build "DustyPig.Mobile.Android/DustyPig.Mobile.Android.csproj" -c release
        